name: nix-macos

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v8
      with:
        name: jupyterwith
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build tests -A build -A kernel-tests.core
