name: nix-linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        skip_adding_nixpkgs_channel: true
    - uses: cachix/cachix-action@v10
      with:
        name: jupyterwith
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build tests -A build -A kernel-tests.core
